stages:
  collect:
    cmd: python scripts/collect_data.py
    deps:
    - scripts/collect_data.py
    outs:
    - data/raw/weather_data.csv
  
  preprocess:
    cmd: python scripts/preprocess_data.py
    deps:
    - scripts/preprocess_data.py
    - data/raw/weather_data.csv
    outs:
    - data/processed/processed_data.csv
  
  train:
    cmd: python scripts/train_model.py
    deps:
    - scripts/train_model.py
    - data/processed/processed_data.csv
    outs:
    - models/model.pkl

